---
- name: Launch an Amazon EC2 instance from localhost
  hosts: localhost
  connection: local
  gather_facts: False

  roles:
    - create_ec2


- name: Setup hosts
  hosts: launched
  become: True

  roles:
    - iptables
    - docker
    - nginx
