---
- name: Create security group
  ec2_group:
    name: "{{ group }}"
    description: 'Allow HTTP, HTTPS and SSH'
    region: "{{ region }}"
    ec2_access_key: "{{ aws_access_key }}"
    ec2_secret_key: "{{ aws_secret_key }}"
    # Inbound rules.
    rules:
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 443
        to_port: 443
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0

    # Outbound rules.
    rules_egress:
      - proto: all
        from_port: 0
        to_port: 65535
        cidr_ip: 0.0.0.0/0

- name: Launching an EC2 Instance
  ec2:
    key_name: "{{ keypair }}"
    instance_type: "{{ instance_type }}"
    image: "{{ ami }}"
    wait: yes
    group: "{{ group }}"
    instance_tags:
       Name: "{{ tag }}-01"
    exact_count: 1
    count_tag:
       Name: "{{ tag }}-01"
    region: "{{ region }}"
  register: ec2

- name: Wait for SSH to come up
  wait_for:
        host: "{{ item.public_dns_name }}"
        port: 22
        delay: 60
        timeout: 320
        state: started
  with_items: "{{ ec2.instances }}"

- name: Add the new instance to the inventory
  add_host: hostname={{ item.public_ip }} groupname=launched ansible_user=ec2-user
  with_items: "{{ ec2.tagged_instances }}"

- name: Get rid of SSH "Are you sure you want to continue connecting (yes/no)?" query
  shell: ssh-keyscan -t rsa "{{ item.public_ip }}" >> $HOME/.ssh/known_hosts
  with_items: "{{ ec2.instances }}"
  run_once: True
